### ISSUE TITLE
[BUG] Failed UT 

### ISSUE THREAD

**Issue by Hailong-am** [opensearch-project/alerting-dashboards-plugin#1039]
**What is the bug?**

public/components/FeatureAnywhereContextMenu/AddAlertingMonitor/AddAlertingMonitor.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/ihailong/code/OpenSearch-Dashboards/node_modules/monaco-editor/esm/vs/editor/editor.api.js:5
    import { EDITOR_DEFAULTS } from './common/config/editorOptions.js';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      31 | /* eslint-disable @osd/eslint/module_migration */
      32 |
    > 33 | import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';
         | ^
      34 |
      35 | import 'monaco-editor/esm/vs/base/common/worker/simpleWorker';
      36 | import 'monaco-editor/esm/vs/base/worker/defaultWorkerFactory';

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (../../packages/osd-monaco/src/monaco.ts:33:1)
      at Object.<anonymous> (../../packages/osd-monaco/src/index.ts:31:1)
      at Object.<anonymous> (../../src/plugins/data/public/antlr/opensearch_sql/code_completion.ts:6:1)
      at Object.<anonymous> (../../src/plugins/data/public/plugin.ts:96:1)
      at Object.<anonymous> (../../src/plugins/data/public/index.ts:503:1)
      at Object.<anonymous> (../../src/plugins/saved_objects/public/saved_object/helpers/serialize_saved_object.ts:34:1)
      at Object.<anonymous> (../../src/plugins/saved_objects/public/saved_object/helpers/build_saved_object.ts:34:1)
      at Object.<anonymous> (../../src/plugins/saved_objects/public/saved_object/saved_object.ts:42:1)
      at Object.<anonymous> (../../src/plugins/saved_objects/public/saved_object/index.ts:31:1)

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by riysaxen-amzn** [comment]
closing this in favor of #1040
