### ISSUE TITLE
[2.0.0][Distribution]Remove rc1 qualifier reference in your code of 2.0 branch

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/alerting-dashboards-plugin#233]
We are coming from this issue: https://github.com/opensearch-project/opensearch-build/issues/2078 in your `2.0` branch.

### Note: This needs to be completed before `05/17` which is feature freeze day for `2.0.0-GA`.

1. If you have `OpenSearch plugin` in your repo, make sure your `build.gradle` remove `rc1` reference, leave as `""`.
```
opensearch_version = System.getProperty("opensearch.version", "2.0.0-SNAPSHOT")
buildVersionQualifier = System.getProperty("build.version_qualifier", "")
```

2. If you have `OpenSearch-Dashboards plugin` in your repo, make sure your `package.json` remove `rc1` reference, leave as `2.0.0.0`.
```
"version": "2.0.0.0",
```

3. If you have any `.github/workflows` contains hardcode `rc1` reference, please remove.

Thanks.

**Comment by peterzhuamazon** [comment]
@AWSHurneyt @lezzago please backport your changes to 2.0 branch.
Thanks.

**Comment by peterzhuamazon** [comment]
```
+ echo 'COPY alertingDashboards.zip'
COPY alertingDashboards.zip
+ cp -r ../OpenSearch-Dashboards/plugins/alertingDashboards/build/alertingDashboards-2.0.0.zip builds/plugins/
+ rm -rf ../OpenSearch-Dashboards/plugins/alertingDashboards
2022-05-16 17:16:46 INFO     Recording plugins artifact for alertingDashboards: plugins/alertingDashboards-2.0.0.zip (from /tmp/tmp2_t31f5u/alertingDashboards/builds/plugins/alertingDashboards-2.0.0.zip)
2022-05-16 17:16:46 ERROR    Error building alertingDashboards, retry with: ./build.sh manifests/2.0.0/opensearch-dashboards-2.0.0.yml --component alertingDashboards
Traceback (most recent call last):
  File "/var/jenkins/workspace/distribution-build-opensearch-dashboards/src/build_workflow/opensearch_dashboards/build_artifact_check_plugin.py", line 35, in check
    config.check_value_in("version", self.target.compatible_component_versions)
  File "/var/jenkins/workspace/distribution-build-opensearch-dashboards/src/system/config_file.py", line 66, in check_value_in
    raise ConfigFile.UnexpectedKeyValuesError(key, expected, value)
system.config_file.UnexpectedKeyValuesError: Expected to have version=any of ['2.0.0.0'], but was '2.0.0.0-rc1'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./src/run_build.py", line 80, in <module>
    sys.exit(main())
  File "./src/run_build.py", line 69, in main
    builder.export_artifacts(build_recorder)
  File "/var/jenkins/workspace/distribution-build-opensearch-dashboards/src/build_workflow/builder_from_source.py", line 65, in export_artifacts
    build_recorder.record_artifact(self.component.name, artifact_type, relative_path, absolute_path)
  File "/var/jenkins/workspace/distribution-build-opensearch-dashboards/src/build_workflow/build_recorder.py", line 40, in record_artifact
    BuildArtifactChecks.check(self.target, artifact_type, artifact_file)
  File "/var/jenkins/workspace/distribution-build-opensearch-dashboards/src/build_workflow/build_artifact_checks.py", line 42, in check
    instance.check(path)
  File "/var/jenkins/workspace/distribution-build-opensearch-dashboards/src/build_workflow/opensearch_dashboards/build_artifact_check_plugin.py", line 38, in check
    raise BuildArtifactCheck.BuildArtifactInvalidError(path, e.__str__())
build_workflow.build_artifact_check.BuildArtifactInvalidError: Artifact alertingDashboards-2.0.0.zip is invalid. Expected to have version=any of ['2.0.0.0'], but was '2.0.0.0-rc1'.

```

**Comment by lezzago** [comment]
#239 Backport PR has been merged
