### ISSUE TITLE
[BUG] Cannot create monitors/alerts on OpenSearch-Dashboards:2.0.0

### ISSUE THREAD

**Issue by DogukanL** [opensearch-project/alerting-dashboards-plugin#254]
**Cannot create monitors/alerts**

With the new update I can create a new notification channel just fine. But when I try to create a monitor, I get the exceptions below. The alerting plugin is looking for the .opendistro-alerting-config index which the cluster does not seem to create automatically like it does with other system indices.

**To Reproduce**
I am using docker to bring up my cluster:
```yaml
version: '3.9'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.0.0
    container_name: opensearch-node
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net
    
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.0.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node:9200"]'
    networks:
      - opensearch-net

volumes:
  opensearch-data:

networks:
  opensearch-net:
```

**OpenSearch Version**
opensearchproject/opensearch:2.0.0

**Dashboards Version**
opensearchproject/opensearch-dashboards:2.0.0

**Plugins**
- opensearch-alerting
- opensearch-anomaly-detection
- opensearch-asynchronous-search
- opensearch-cross-cluster-replication
- opensearch-index-management
- opensearch-job-scheduler
- opensearch-knn
- opensearch-ml
- opensearch-notifications
- opensearch-notifications-core
- opensearch-observability
- opensearch-performance-analyzer
- opensearch-reports-scheduler
- opensearch-security
- opensearch-sql

**Host/Environment**
 - centos7
 - ubuntu 21.10
 - Google Chrome 101.0.4951.41 (Official Build) (64-bit)
 - Docker version: 20.10.16

**Errors**

*When I click on "Add Trigger" under "Create Monitor"*

```
opensearch-node          | [2022-05-30T14:16:17,825][ERROR][o.o.a.u.AlertingException] [opensearch-node] Alerting error: [.opendistro-alerting-config] IndexNotFoundException[no such index [.opendistro-alerting-config]]
opensearch-dashboards    | Alerting - MonitorService - searchMonitor: StatusCodeError: [alerting_exception] Configured indices are not found: [.opendistro-alerting-config]

```

*When I try to create the monitor*

```
opensearch-node          | [2022-05-30T14:16:17,870][WARN ][r.suppressed             ] [opensearch-node] path: /_plugins/_alerting/monitors/_execute, params: {dryrun=false}
opensearch-node          | java.lang.IllegalStateException: Can't get text on a START_OBJECT at 1:932
opensearch-node          | 	at org.opensearch.common.xcontent.json.JsonXContentParser.text(JsonXContentParser.java:97) ~[opensearch-x-content-2.0.0.jar:2.0.0]
opensearch-node          | 	at org.opensearch.alerting.model.action.ActionExecutionScope$Companion.parse(ActionExecutionScope.kt:60) ~[?:?]
opensearch-node          | 	at org.opensearch.alerting.model.action.ActionExecutionPolicy$Companion.parse(ActionExecutionPolicy.kt:61) ~[?:?]
opensearch-node          | 	at org.opensearch.alerting.model.action.Action$Companion.parse(Action.kt:156) ~[?:?]
opensearch-node          | 	at org.opensearch.alerting.model.QueryLevelTrigger$Companion.parseInner(QueryLevelTrigger.kt:162) ~[?:?]
opensearch-node          | 	at org.opensearch.alerting.model.Trigger$Companion.parse(Trigger.kt:50) ~[?:?]
opensearch-node          | 	at org.opensearch.alerting.model.Monitor$Companion.parse(Monitor.kt:279) ~[?:?]
opensearch-node          | 	at org.opensearch.alerting.resthandler.RestExecuteMonitorAction.prepareRequest$lambda-0(RestExecuteMonitorAction.kt:67) ~[?:?]
opensearch-node          | 	at org.opensearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:125) ~[opensearch-2.0.0.jar:2.0.0]
opensearch-node          | 	at org.opensearch.security.filter.SecurityRestFilter$1.handleRequest(SecurityRestFilter.java:128) ~[?:?]
opensearch-node          | 	at org.opensearch.rest.RestController.dispatchRequest(RestController.java:311) [opensearch-2.0.0.jar:2.0.0]
opensearch-node          | 	at org.opensearch.rest.RestController.tryAllHandlers(RestController.java:397) [opensearch-2.0.0.jar:2.0.0]
opensearch-node          | 	at org.opensearch.rest.RestController.dispatchRequest(RestController.java:240) [opensearch-2.0.0.jar:2.0.0]
opensearch-node          | 	at org.opensearch.security.ssl.http.netty.ValidatingDispatcher.dispatchRequest(ValidatingDispatcher.java:63) [opensearch-security-2.0.0.0.jar:2.0.0.0]
opensearch-node          | 	at org.opensearch.http.AbstractHttpServerTransport.dispatchRequest(AbstractHttpServerTransport.java:366) [opensearch-2.0.0.jar:2.0.0]
opensearch-node          | 	at org.opensearch.http.AbstractHttpServerTransport.handleIncomingRequest(AbstractHttpServerTransport.java:445) [opensearch-2.0.0.jar:2.0.0]
opensearch-node          | 	at org.opensearch.http.AbstractHttpServerTransport.incomingRequest(AbstractHttpServerTransport.java:356) [opensearch-2.0.0.jar:2.0.0]
opensearch-node          | 	at org.opensearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:55) [transport-netty4-client-2.0.0.jar:2.0.0]
opensearch-node          | 	at org.opensearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:41) [transport-netty4-client-2.0.0.jar:2.0.0]
opensearch-node          | 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at org.opensearch.http.netty4.Netty4HttpPipeliningHandler.channelRead(Netty4HttpPipeliningHandler.java:71) [transport-netty4-client-2.0.0.jar:2.0.0]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1371) [netty-handler-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234) [netty-handler-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283) [netty-handler-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) [netty-codec-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) [netty-codec-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:623) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:586) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-common-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.73.Final.jar:4.1.73.Final]
opensearch-node          | 	at java.lang.Thread.run(Thread.java:833) [?:?]

```

# UPDATE:

Upon further inspection, I've found that ".opendistro-alerting-config" index not existing before trying to create a monitor does not seem to be the issue, or at least from what I can tell.

I've cloned every repo under opensearch-project and used ag to find where "system_indices" are mentioned and I really couldn't find a function, class or a piece of code that creates all system_indices as a bootstrap process.

Long story short I think the issue is with the API because:

### This is okay
It automatically creates the ".opendistro-alerting-config" and the monitor works.

```javascript
POST _plugins/_alerting/monitors
{
  "name": "MyTestMonitor",
  "type": "monitor",
  "monitor_type": "cluster_metrics_monitor",
  "enabled": true,
  "schedule": {
    "period": {
      "interval": 1,
      "unit": "MINUTES"
    }
  },
  "inputs": [
    {
      "uri": {
        "api_type": "CLUSTER_HEALTH",
        "path": "_cluster/health/",
        "path_params": "",
        "url": "http://localhost:9200/_cluster/health/"
      }
    }
  ],
  "triggers": [
    {
      "name": "MyTestTrigger",
      "severity": "1",
      "condition": {
        "script": {
          "lang": "painless",
          "source": "return true"
        }
      },
      "actions": [
        {
          "name": "MyTestAction",
          "destination_id": "fEAKFYEBpplJRNa113rm",
          "subject_template": {
            "lang": "mustache",
            "source": "MyTestSubject"
          },
          "message_template": {
            "lang": "mustache",
            "source": "Monitor {{ctx.monitor.name}} just entered alert status. Please investigate the issue.\n  - Trigger: {{ctx.trigger.name}}\n  - Severity: {{ctx.trigger.severity}}\n  - Period start: {{ctx.periodStart}}\n  - Period end: {{ctx.periodEnd}}"
          },
          "throttle_enabled": false
        }
      ],
      "min_time_between_executions": null,
      "rolling_window_size": null
    }
  ]
}
```

### This is NOT OKAY
```javascript
POST _plugins/_alerting/monitors
{
  "name": "MyTestMonitor",
  "type": "monitor",
  "monitor_type": "cluster_metrics_monitor",
  "enabled": true,
  "schedule": {
    "period": {
      "interval": 1,
      "unit": "MINUTES"
    }
  },
  "inputs": [
    {
      "uri": {
        "api_type": "CLUSTER_HEALTH",
        "path": "_cluster/health/",
        "path_params": "",
        "url": "http://localhost:9200/_cluster/health/"
      }
    }
  ],
  "triggers": [
    {
      "name": "MyTestTrigger",
      "severity": "1",
      "condition": {
        "script": {
          "lang": "painless",
          "source": "return true"
        }
      },
      "actions": [
        {
          "name": "MyTestAction",
          "destination_id": "fEAKFYEBpplJRNa113rm",
          "subject_template": {
            "lang": "mustache",
            "source": "MyTestSubject"
          },
          "message_template": {
            "lang": "mustache",
            "source": "Monitor {{ctx.monitor.name}} just entered alert status. Please investigate the issue.\n  - Trigger: {{ctx.trigger.name}}\n  - Severity: {{ctx.trigger.severity}}\n  - Period start: {{ctx.periodStart}}\n  - Period end: {{ctx.periodEnd}}"
          },
          "throttle_enabled": false,
          "action_execution_policy": {
            "action_execution_scope": {
              "per_alert": {
                "actionable_alerts": [
                  {
                    "value": "DEDUPED",
                    "label": "De-duplicated"
                  },
                  {
                    "value": "NEW",
                    "label": "New"
                  }
                ]
              }
            }
          }
        }
      ],
      "min_time_between_executions": null,
      "rolling_window_size": null
    }
  ]
}
```
The "action_execution_policy" map somehow creates a problem and results in the following error:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_state_exception",
        "reason" : "Can't get text on a START_OBJECT at 49:19"
      }
    ],
    "type" : "illegal_state_exception",
    "reason" : "Can't get text on a START_OBJECT at 49:19"
  },
  "status" : 500
}
```

### Similarly

```javascript
POST _plugins/_alerting/monitors
{
    "name": "MyTestMonitor",
    "type": "monitor",
    "monitor_type": "cluster_metrics_monitor",
    "enabled": true,
    "schedule": {
        "period": {
            "interval": 1,
            "unit": "MINUTES"
        }
    },
    "inputs": [
        {
            "uri": {
                "api_type": "CLUSTER_HEALTH",
                "path": "_cluster/health/",
                "path_params": "",
                "url": "http://localhost:9200/_cluster/health/"
            }
        }
    ],
    "triggers": [
        {
            "name": "MyTestTrigger",
            "severity": "1",
            "condition": {
                "script": {
                    "lang": "painless",
                    "source": "ctx.results[0].status == \"green\""
                }
            },
            "actions": [
                {
                    "name": "MyTestAction",
                    "destination_id": "fEAKFYEBpplJRNa113rm",
                    "subject_template": {
                        "lang": "mustache",
                        "source": "MyTestSubject"
                    },
                    "message_template": {
                        "lang": "mustache",
                        "source": "Monitor {{ctx.monitor.name}} just entered alert status. Please investigate the issue.\n  - Trigger: {{ctx.trigger.name}}\n  - Severity: {{ctx.trigger.severity}}\n  - Period start: {{ctx.periodStart}}\n  - Period end: {{ctx.periodEnd}}"
                    },
                    "throttle_enabled": false,
                    "action_execution_policy": {
                        "action_execution_scope": "per_execution"
                    }
                }
            ],
            "min_time_between_executions": null,
            "rolling_window_size": null
        }
    ]
}
```

This time "action_execution_scope" is "per_execution" instead of "per_alert". And this version causes:

```javascript
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parsing_exception",
        "reason" : "Failed to parse object: expecting token of type [START_OBJECT] but found [VALUE_STRING]",
        "line" : 46,
        "col" : 51
      }
    ],
    "type" : "parsing_exception",
    "reason" : "Failed to parse object: expecting token of type [START_OBJECT] but found [VALUE_STRING]",
    "line" : 46,
    "col" : 51
  },
  "status" : 400
}

```
The last 2 erronous requests are what opensearch dashboards sends (minus the "ui_metadata" key) when you are trying to create a monitor.

I don't know whether this is dashboards not adhering to any API changes or an internal problem where opensearch is meant to parse the "action_execution_policy" maps above. Just my two cents.

# UPDATE 2

I think I found the problem. Opensearch excepts a list of strings for "actionable_alerts" key, [see](https://github.com/opensearch-project/alerting/blob/036947c013a2370527df40c79e1fcbed075e3f74/alerting/src/main/kotlin/org/opensearch/alerting/model/action/ActionExecutionScope.kt#L59). Wheras dashboards send a list of dictionaries such as:
```javascript
 {
    "value": "DEDUPED",
    "label": "De-duplicated"
  },
  {
    "value": "NEW",
    "label": "New"
}
```

**Comment by DogukanL** [comment]
Hey @kavilla,

Thanks for getting back to me! To give you a little more insight:

I have experienced the same issue on my test cluster I have updated from 1.3.2 to 2.0.0 with no apparent problems by changing container images and some breaking config settings in opensearch.yml. Prior to the update, there was already an .opendistro_security index created by the securityadmin.sh. So neither the securityadmin script nor the demo script has run on that cluster after the update.

Thinking this could be caused by the update, I have deployed the fresh 2.0.0 cluster above and still got the same errors.

**Comment by ravikiranvuppu** [comment]
Hello, 

I have run into the same issue and currently stuck with same error being thrown no matter whatever tried. I tried multiple notification types and it looks like monitor doesn't like the action block with notification channel set and it doesn't even let you save the config or test fire action with 'send message' and keeps throwing same  java.lang.IllegalStateException: Can't get text on a START_OBJECT error.

**Comment by kavilla** [comment]
@AWSHurneyt, @lezzago, seems like a duplicate came up https://github.com/opensearch-project/alerting-dashboards-plugin/issues/260. This could be due to the backend plugin but I was trying to see if any breaking changes were called in configs in weren't seeing anything.

Do y'all have some insight here?

**Comment by DogukanL** [comment]
@kavilla I think I identified the problem. I updated the issue itself rather than commenting them. You can check out the updates.

**Comment by lezzago** [comment]
The attached plugin artifact ([alertingDashboards-2.0.0.0.zip](https://github.com/opensearch-project/alerting-dashboards-plugin/files/8835333/alertingDashboards-2.0.0.0.zip)) can be used to reinstall the alerting plugin. 

To reinstall the plugin, please follow these steps outlined [here](https://opensearch.org/docs/latest/dashboards/install/plugins/#update-plugins).

To build the plugin artifact manually, please follow these [steps](https://github.com/opensearch-project/alerting-dashboards-plugin/blob/main/DEVELOPER_GUIDE.md#build).

**Comment by pietrogu** [comment]
> The attached plugin artifact ([alertingDashboards-2.0.0.0.zip](https://github.com/opensearch-project/alerting-dashboards-plugin/files/8835333/alertingDashboards-2.0.0.0.zip)) can be used to reinstall the alerting plugin.
> 
> To reinstall the plugin, please follow these steps outlined [here](https://opensearch.org/docs/latest/dashboards/install/plugins/#update-plugins).
> 
> To build the plugin artifact manually, please follow these [steps](https://github.com/opensearch-project/alerting-dashboards-plugin/blob/main/DEVELOPER_GUIDE.md#build).

Hi,

could you give the instruction to use this in a docker environment?

Thank you
Pietro

**Comment by DogukanL** [comment]
@lezzago @AWSHurneyt 

I still have the same issue creating cluster level metrics monitor after applying the patch.

My Dockerfile:
```Dockerfile
FROM opensearchproject/opensearch-dashboards:2.0.0
RUN bin/opensearch-dashboards-plugin remove alertingDashboards \
    && bin/opensearch-dashboards-plugin install https://github.com/opensearch-project/alerting-dashboards-plugin/files/8835333/alertingDashboards-2.0.0.0.zip
```

My compose file is the same as above, except I'm using the new image.

**Comment by lezzago** [comment]
@pietrogu, you can reinstall it using: https://opensearch.org/docs/latest/opensearch/install/docker#customize-the-docker-image

@DogukanL, did you restart the OpenSearch-Dashboards?

**Comment by DogukanL** [comment]
@lezzago @kavilla 

Okay sorry, my bad. It still shows "failed to load destinations" when you click "add trigger" **until after** you've created your first monitor. So I just assumed it didn't work. When I clicked create the monitor was created successfully and subsequent create actions do not have the error pop up on the bottom right. The issue seems to be solved, except the misleading error message.

**Comment by pietrogu** [comment]
@lezzago the issue was accidentaly closed by another user.
Could you please re-open it?
Also could you share the steps to implement the workaround in a docker environment?

**Comment by mateuszk-gain** [comment]
@pietrogu 

https://github.com/opensearch-project/alerting/issues/470

**Comment by lezzago** [comment]
Hi everyone, we have now release OpenSearch 2.0.1, which includes the patch to fix this problem. We recommend upgrading the 2.0 clusters to 2.0.1 as there are other fixes mentioned [here](https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-2.0.1.md)

**Comment by anubisg1** [comment]
i'm using 2.2.1 and i still see this.

the cluster was created using the opensearch-k8s-operator and installed in version 1.3.4 , then upgraded to 2.2.1

**Comment by kksaha** [comment]
While updating the monitor, even if we are using version 2.2.0, the problem persists.

<img width="362" alt="image" src="https://user-images.githubusercontent.com/34137960/212662224-71415b9a-f13c-453f-9eed-47d1a879b66d.png">
