### ISSUE TITLE
[BUG] Notification Channels list shows objects multiple times - breaking notifications

### ISSUE THREAD

**Issue by tomuk5** [opensearch-project/alerting-dashboards-plugin#795]
In the Monitor creation or modification screen, the notification channels dropdown menu shows the list of configured email and email group channels multiple times over.
Only one of the duplicated choices results in the monitor working, selection of a non-working channel results in the error displayed to the user: `For input string: "NOT_FOUND"`

in the oplog on the opensearch node, the below error is seen:
```[2023-11-07T14:39:36,075][INFO ][o.o.n.i.ConfigIndexingActions] [graylog-ingest1] notifications:NotificationConfig-get org.opensearch.commons.notifications.action.GetNotificationConfigRequest@61797697
[2023-11-07T14:39:36,075][INFO ][o.o.n.i.ConfigIndexingActions] [graylog-ingest1] notifications:NotificationConfig-info ns7q4IoBZokGLCNvK7Zm
[2023-11-07T14:39:36,082][INFO ][o.o.n.s.SendMessageActionHelper] [graylog-ingest1] notifications:getSingleConfig-get ns7q4IoBZokGLCNvK7Zm
[2023-11-07T14:39:36,086][INFO ][o.o.c.n.m.NotificationConfig] [graylog-ingest1] non-allowed config type for Status
[2023-11-07T14:39:36,087][WARN ][o.o.n.s.SendMessageActionHelper] [graylog-ingest1] Cannot send message to destination for config id :ns7q4IoBZokGLCNvK7Zm
[2023-11-07T14:39:36,087][INFO ][o.o.c.n.m.NotificationConfig] [graylog-ingest1] non-allowed config type for Status
[2023-11-07T14:39:36,089][WARN ][o.o.n.a.PluginBaseAction ] [graylog-ingest1] notifications:IllegalArgumentException:
java.lang.NumberFormatException: For input string: "NOT_FOUND"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
        at org.opensearch.notifications.send.SendMessageActionHelper.executeRequest(SendMessageActionHelper.kt:103) ~[?:?]
        at org.opensearch.notifications.send.SendMessageActionHelper$executeRequest$1.invokeSuspend(SendMessageActionHelper.kt) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.8.21.jar:1.8.21-release-380(1.8.21)]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [kotlin-stdlib-1.8.21.jar:1.8.21-release-380(1.8.21)]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
```

querying `GET _plugins/_notifications/configs` shows that there are 3x email groups configured, but the dropdown list shows 9x (3x duplicated lots of 3x)

**How can one reproduce the bug?**
1. Go to Alerting>Monitors
2. Edit or create a monitor
3. Scroll Down to actions and then notifications
4. click on the Channel dropdown list
5. entries for channels (email and email groups) are displayed multiple times in the list

**What is the expected behavior?**
The Notification emails/email groups be shown correctly

**What is your host/environment?**
 - OS: Debian 11
 - Version 2.11

**Do you have any screenshots?**
![Screenshot from 2023-11-07 14-34-36](https://github.com/opensearch-project/alerting-dashboards-plugin/assets/5192633/67a19121-7af4-4f0e-931b-98bd25ef86ce)
![Screenshot from 2023-11-07 14-34-59](https://github.com/opensearch-project/alerting-dashboards-plugin/assets/5192633/46130277-7758-4592-a6de-6261b6ce86ce)
![Screenshot from 2023-11-07 14-47-03](https://github.com/opensearch-project/alerting-dashboards-plugin/assets/5192633/57bed27b-198c-412d-9b85-756a54559366)

**Comment by pbn4** [comment]
I also face this issue, @amsiglan I see you self assigned yourself not so long ago, do you plan to work on this?

**Comment by AWSHurneyt** [comment]
Closing as the fix PR has been merged. If this is still an issue, please feel free to reopen this issue.

**Comment by tomuk5** [comment]
This is occurring again in version 2.19.1 - same as before, appears to be a regression

**Comment by AWSHurneyt** [comment]
@tomuk5 reopening. If you have any more details about the environment experiencing the issue, please share them here to help us reproduce.

**Comment by tomuk5** [comment]
In the Monitor creation or modification screen, the notification channels dropdown menu shows the list of configured email and email group channels multiple times over. (same as previous screenshots)
Only one of the duplicated choices results in the monitor working, selection of a non-working channel results does not result in immediate error, but when sending test messages give the error `Error running com.github.mustachejava.codes.DefaultMustache@5da49b33`.

**How can one reproduce the bug?**
Steps to reproduce the behavior:

Go to Alerting>Monitors
Edit or create a monitor
Scroll Down to actions and then notifications
click on the Channel dropdown list
entries for channels (email and email groups) are displayed multiple times in the list
What is the expected behavior?
The Notification emails/email groups be shown correctly

**What is your host/environment?**

OS: Debian 12
Version 2.19.1
